name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *' # 每 6 小时自动运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main # 截图显示你的分支是 main

      - name: Sync with Upstream
        uses: wei/pull@v3
        with:
          upstream_package_repository: hjdhnx/drpy-node
          upstream_branch: master # 原作者的主分支通常是 master
          target_branch: main     # 你的主分支是 main
          github_token: ${{ secrets.GITHUB_TOKEN }}
